/*
 * Autogenerated From files:
 * ..\Languages\English\Keyed\ScenParts.xml
*/

using System;
using Verse;

namespace R.MoreScenarioParts {
	public static partial class String {
		// ..\Languages\English\Keyed\ScenParts.xml
		public static string MSP_Gender_All => "MSP_Gender_All".Translate();
		public static string MSP_Gender_Male => "MSP_Gender_Male".Translate();
		public static string MSP_Gender_Female => "MSP_Gender_Female".Translate();
		public static string MSP_Gender => "MSP_Gender".Translate();
		public static string MSP_Faction => "MSP_Faction".Translate();
		public static string MSP_Undefined => "MSP_Undefined".Translate();
		public static string MSP_Age => "MSP_Age".Translate();
		public static string MSP_PawnContext_All => "MSP_PawnContext_All".Translate();
		public static string MSP_PawnContext_PlayerStarter => "MSP_PawnContext_PlayerStarter".Translate();
		public static string MSP_PawnContext_PlayerNonStarter => "MSP_PawnContext_PlayerNonStarter".Translate();
		public static string MSP_PawnContext_NonPlayer => "MSP_PawnContext_NonPlayer".Translate();
		public static string MSP_PawnContext_Player => "MSP_PawnContext_Player".Translate();
		public static string MSP_PawnContext_Faction => "MSP_PawnContext_Faction".Translate();
		public static string MSP_ThingKind => "MSP_ThingKind".Translate();
		public static string MSP_Thing => "MSP_Thing".Translate();
		public static string MSP_Stuff => "MSP_Stuff".Translate();
		public static string MSP_Amount => "MSP_Amount".Translate();
		public static string MSP_Equip => "MSP_Equip".Translate();
		public static string MSP_ThingKind_Weapon => "MSP_ThingKind_Weapon".Translate();
		public static string MSP_ThingKind_Aparrel => "MSP_ThingKind_Aparrel".Translate();
		public static string MSP_ThingKind_Building => "MSP_ThingKind_Building".Translate();
		public static string MSP_ThingKind_Items => "MSP_ThingKind_Items".Translate();
		public static string MSP_Context => "MSP_Context".Translate();
		public static string MSP_Chance => "MSP_Chance".Translate();
		public static string MSP_Radius => "MSP_Radius".Translate();
	}
}